name: pqchat-c CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    env:
      OPENSSL_PREFIX: ${{ github.workspace }}/opt/openssl-3.5
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git ca-certificates pkg-config patchelf

      - name: Cache OpenSSL 3.5 build
        id: cache-ossl
        uses: actions/cache@v4
        with:
          path: ${{ env.OPENSSL_PREFIX }}
          key: ossl-3.5.0-${{ runner.os }}-v1

      - name: Build & install OpenSSL 3.5.0 (if cache miss)
        if: steps.cache-ossl.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 --branch openssl-3.5.0 https://github.com/openssl/openssl.git
          cd openssl
          ./Configure --prefix="${OPENSSL_PREFIX}" linux-x86_64
          make -j"$(nproc)"
          make install_sw

      - name: Force RPATH on installed openssl
        run: |
          ls -l "${OPENSSL_PREFIX}/lib"
          patchelf --set-rpath "${OPENSSL_PREFIX}/lib" "${OPENSSL_PREFIX}/bin/openssl"
          ldd "${OPENSSL_PREFIX}/bin/openssl" | egrep 'ssl|crypto'

      - name: Export OpenSSL paths to environment
        run: |
          echo "${OPENSSL_PREFIX}/bin" >> "$GITHUB_PATH"
          echo "LD_LIBRARY_PATH=${OPENSSL_PREFIX}/lib" >> "$GITHUB_ENV"
          echo "OPENSSL_MODULES=${OPENSSL_PREFIX}/lib/ossl-modules" >> "$GITHUB_ENV"
          echo "PKG_CONFIG_PATH=${OPENSSL_PREFIX}/lib/pkgconfig" >> "$GITHUB_ENV"

      - name: Show openssl version and groups
        run: |
          which openssl
          ldd "$(which openssl)" | egrep 'ssl|crypto'
          openssl version -a
          openssl list -tls-groups | tr '\n' ' ' | sed 's/  */ /g'

      - name: Generate test certs (ML-DSA-65)
        run: |
          OPENSSL=openssl ./scripts/gen_certs.sh

      - name: Build project
        run: |
          make clean
          make
          ldd ./server | egrep 'ssl|crypto'
          ldd ./client | egrep 'ssl|crypto'

      - name: Smoke test (self client)
        run: |
          set -e
          ./server &
          PID=$!
          sleep 1
          printf "hello\n" | ./client | tee /tmp/out.txt
          kill $PID
          grep -q "echo: hello" /tmp/out.txt

      - name: Smoke test (openssl s_client)
        run: |
          ./server &
          PID=$!
          sleep 1
          openssl s_client -connect [::1]:4433 -tls1_3 -groups MLKEM768 -CAfile cert/ca.crt </dev/null 2>&1 | tee /tmp/sclient.txt || true
          kill $PID
          grep -q "Negotiated TLS1.3 group: MLKEM768" /tmp/sclient.txt
